### ISSUE TITLE
메세지 전송

### ISSUE THREAD

**Issue by im3zero** [MechanIT/Speech-and-object-recognition-for-elderly-people-living-alone#2]
비상 연락망 이슈:
이메일로는 전송이 되는데, 메세지나 전화는 아직 해결이 되지 않았습니다.

**Comment by Jiisou** [comment]
이메일과 SMS를 보내는 방법에 차이가 있는 이유는 주로 두 가지 통신 방식의 특성, 인프라 및 표준이 다르기 때문입니다. 이들 각각의 차이를 이해하면 왜 다른 방식이 필요한지 알 수 있습니다.

이메일과 SMS의 차이점
통신 프로토콜:

이메일: 이메일은 SMTP(Simple Mail Transfer Protocol)를 사용하여 인터넷을 통해 전송됩니다. SMTP는 표준화된 프로토콜로, 전 세계의 모든 이메일 서버가 이를 이해하고 처리할 수 있습니다.
SMS: SMS는 휴대전화 네트워크를 통해 전송됩니다. 이를 위해 SMS 게이트웨이를 통해 텍스트 메시지를 이동통신사의 SMSC(Short Message Service Center)로 전달해야 합니다.
전송 경로:

이메일: 이메일은 인터넷을 통해 전달됩니다. SMTP 서버가 발신자에서 수신자로 이메일을 전달하는 일련의 서버를 거칩니다.
SMS: SMS는 이동통신 네트워크를 통해 전달됩니다. 일반적으로 SMS 게이트웨이를 통해 이동통신사의 SMSC로 전달되며, 여기서 다시 수신자의 휴대전화로 전달됩니다.
서비스 제공업체:

이메일: 누구나 이메일 서버를 운영할 수 있습니다. 무료 또는 유료 이메일 서비스를 제공하는 다양한 업체가 있습니다 (예: Gmail, Outlook).
SMS: SMS는 이동통신사와의 계약이 필요하며, 일반 사용자는 직접 SMS를 보내는 인프라를 갖추기 어렵습니다. 따라서 Twilio와 같은 SMS 게이트웨이 서비스를 통해 이동통신사 네트워크와 연결됩니다.
비용:

이메일: 대부분의 이메일은 무료로 전송됩니다. 단, 대량 이메일 발송 시에는 서비스 요금이 발생할 수 있습니다.
SMS: 일반적으로 각 SMS 메시지에 비용이 부과됩니다. 이동통신사나 SMS 게이트웨이 서비스 제공업체에 따라 비용이 달라집니다.
